name: 'Contensis cli action'
description: 'A GitHub Action for interacting with a Contensis CMS via the cli'
author: 'Zengenti'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  alias:
    description: 'The Contensis cloud alias to connect to'
    required: true
  project-id:
    description: 'The id of the project to connect to'
    required: false
    default: website
  client-id:
    description: 'Client id to connect to the supplied alias'
    required: true
  shared-scret:
    description: 'Shared secret to use with the supplied client id'
    required: true
  block-id:
    description: 'The id of the block to push to'
    required: false
  image-uri:
    description: 'The repository uri of the container image to build the block from'
    required: false
    default: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/app:latest
  auto-release:
    description: 'Whether to release the block upon successful push'
    required: false
    default: false
runs:
  using: 'docker'
  image: ghcr.io/contensis/node-cli/main/app:latest
  pre-entrypoint: contensis connect ${{ inputs.alias }} -id ${{ inputs.client-id }} -s ${{ inputs.shared-secret }} -p ${{ inputs.project-id }}
  entrypoint: |
    if [ -z ${{ inputs.block-id }} ]
    then
      contensis push block ${{ inputs.block-id }} ${{ inputs.image-uri }} --branch ${{ github.ref_name }} ${{ inputs.auto-release && ' --release' }} --commit-message "${{ github.event.head_commit.message }}" --commit-datetime ${{ github.event.head_commit.timestamp }} --author-email ${{ github.event.head_commit.author.email }} --committer-email ${{ github.event.head_commit.committer.email }}
    else
      contensis ${{ inputs.command }}
    fi
