name: 'Contensis cli action'
description: 'A GitHub Action for interacting with a Contensis CMS via the cli'
author: 'Zengenti'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  alias:
    description: 'The Contensis cloud alias to connect to'
    required: true
  project-id:
    description: 'The id of the project to connect to'
    required: false
    default: website
  client-id:
    description: 'Client id to connect to the supplied alias'
    required: true
  shared-secret:
    description: 'Shared secret to use with the supplied client id'
    required: true
  command:
    description: 'Optional: which cli command to run'
    required: false
  cli-version:
    description: 'Optional: pull cli from specified tag. Default: release'
    default: release
outputs:
  command-output:
    description: 'The cli command output'
    value: ${{ steps.cli-command.outputs.command-output }}

runs:
  using: 'composite'
  steps:
    - name: Touch output file
      shell: bash
      run: touch ./output.json

    - name: Pull Contensis CLI docker image and run commands
      id: cli-command
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/contensis/node-cli/main/app:${{ inputs.cli-version }}
        options: -v ./output.json:/usr/src/app/output.json
        run: |
          touch output.json
          contensis
          contensis connect ${{ inputs.alias }} -id ${{ inputs.client-id }} -s ${{ inputs.shared-secret }} -p ${{ inputs.project-id }}
          contensis ${{ inputs.command || '--help' }} --output output.json
          # OUTPUT=`cat output.json`
          # echo "Setting command-output: $OUTPUT"
          # echo "command-output=$OUTPUT" >> $GITHUB_OUTPUT
          # echo "set GITHUB_OUTPUT.command-output OK"

    - name: Set output variables
      id: set
      shell: bash
      run: |
        OUTPUT=`cat output.json`
        echo "Setting command-output: $OUTPUT"
        echo "command-output=$OUTPUT" >> $GITHUB_OUTPUT
        echo "set GITHUB_OUTPUT.command-output OK"
