name: Package arm64 executables CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Ubuntu (arm64)

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            friendlyName: Ubuntu
            fileName: linux

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3

      - uses: uraimo/run-on-arch-action@v2
        name: Build arm64 version (Linux)
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/bin:/artifacts"

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            CONTAINER_CONTEXT: 'true'

          # The shell to run commands with in the container
          shell: /bin/bash

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached.
          install: |
            apt-get update -yq && apt-get -qq -y install gnupg curl
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
            apt-get -qq -y update
            apt-get install -qq -y gnome-keyring \
              libsecret-1-dev \
              dbus-x11 \
              python3-dev \
              yarn \
              npm

          # Produce a binary artifact and place it in the mounted volume
          run: |
            yarn run bootstrap
            yarn run build
            yarn run build:exe
            cd bin && ls -lah
            chmod +x contensis-cli
            ./contensis-cli --version
            cp contensis-cli "/artifacts/contensis-cli-arm64"
            echo "Produced artifact at /artifacts/contensis-cli-arm64"

      - name: Archive packaged artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contensis-cli-${{ env.APP_VERSION }}-${{ matrix.fileName }}-arm64
          path: bin/contensis-cli*
