name: Package executables CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.friendlyName }}

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-20.04, windows-2019, macos-latest]
        include:
          - os: ubuntu-20.04
            friendlyName: Ubuntu
            fileName: linux
          - os: windows-2019
            friendlyName: Windows
            fileName: win
          - os: macos-latest
            friendlyName: macOS
            fileName: mac

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install additional dependencies
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          sudo apt-get -qq -y install gnome-keyring \
                               libsecret-1-dev \
                               dbus-x11 \
                               python3-dev

      - name: Setup os specific environment
        run: |
          yarn run bootstrap
          yarn run build

      - run: |
          echo "Install keyring..."
          pip3 install --upgrade pip
          pip3 install keyring
          echo "Prepare D-Bus session..."
          export $(dbus-launch)
          dbus-launch
          gnome-keyring-daemon --start --daemonize --components=secrets
          echo 'neil' | gnome-keyring-daemon -r -d --unlock
          echo "Create a test key using script..."
          python -c "import keyring;keyring.set_password('system', 'login', 'pwd');"
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        name: Prepare system keyring (Linux)

      - name: Build Windows executable and get app version
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          yarn run build:exe:win
          cd bin
          dir 
          .\contensis-cli --version
          echo "APP_VERSION=$(.\contensis-cli --version)" >> $env:GITHUB_ENV
          exit 0

      - name: Build Linux/macOS executable from os native sources and get app version
        if: ${{ matrix.os != 'windows-2019' }}
        run: |
          yarn run build:exe
          cd bin && ls -lah
          chmod +x contensis-cli
          echo "APP_VERSION=$(./contensis-cli --version)" >> $GITHUB_ENV

      - name: Run some tests with executable
        env:
          CONTAINER_CONTEXT: 'true'
        run: |
          cd bin
          ./contensis-cli connect zenhub-dev -id ${{ secrets.CONTENSIS_CLIENT_ID }} -s ${{ secrets.CONTENSIS_SHARED_SECRET }}
          ./contensis-cli connect zenhub-dev -p migratortron -id ${{ secrets.CONTENSIS_CLIENT_ID }} -s ${{ secrets.CONTENSIS_SHARED_SECRET }}
          ./contensis-cli get entries

      - name: Rename executable to include platform (Linux/macOS)
        if: ${{ matrix.os != 'windows-2019' }}
        run: |
          cd bin
          mv contensis-cli contensis-cli-${{ matrix.fileName }}

      - name: Rename executable to contensis-cli-win.exe
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd bin
          Rename-Item -Path "contensis-cli.exe" -NewName "contensis-cli-win.exe"

      - name: Archive packaged artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contensis-cli-${{ env.APP_VERSION }}-${{ matrix.fileName }}
          path: bin/contensis-cli*
