name: Docker CI

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/app

jobs:
  build:
    name: Build image and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log into container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image and push to ${{ env.APP_IMAGE }}:latest
        run: |
          docker pull ${{ env.APP_IMAGE }}:latest || true
          echo "{\"commitRef\":\"${{ github.sha }}\",\"pipelineIID\":\"null\",\"pipelineUrl\":\"${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}\",\"buildNo\":\"${{ github.run_id }}\",\"branchName\":\"${{ github.ref_name }}\",\"registryImage\":\"${{ env.APP_IMAGE }}\"}" > version.json
          docker build --force-rm --cache-from ${{ env.APP_IMAGE }}:latest -t ${{ env.APP_IMAGE }}:latest -f Dockerfile .
          docker push ${{ env.APP_IMAGE }}:latest

      - name: Push block to Contensis (Test `contensis/block-push` Action)
        id: push-block
        # uses: ./.github/actions/cli-action
        # uses: contensis/cli-action@v1
        uses: ./.github/actions/block-push
        # uses: contensis/block-push@v1
        with:
          block-id: node-cli-ci-block
          auto-release: false
          alias: zenhub-dev
          project-id: contensis
          client-id: ${{ secrets.CONTENSIS_CLIENT_ID }}
          shared-secret: ${{ secrets.CONTENSIS_SHARED_SECRET }}
          tag-repo: true
        secrets: inherit

      # - name: Tag repo with block version
      #   if: (github.ref_name == 'master' || github.ref_name == 'main') && steps.push-block.outputs.block-version != ''
      #   run: |
      #     TAG=${{ steps.push-block.outputs.git-tag }}
      #     VERSION=${{ steps.push-block.outputs.block-version }}
      #     echo "Tagging commit with block version: $VERSION"
      #     git tag $TAG
      #     git push origin $TAG

      # - name: Get entries from Contensis (Test `contensis/cli-action`)
      #   # uses: ./.github/actions/contensis-cli
      #   uses: contensis/cli-action@v1
      #   with:
      #     command: get entries
      #     alias: zenhub-dev
      #     project-id: migratortron
      #     client-id: ${{ secrets.CONTENSIS_CLIENT_ID }}
      #     shared-secret: ${{ secrets.CONTENSIS_SHARED_SECRET }}

  push-block:
    name: Push block
    needs: build
    secrets: inherit
    # uses: ./.github/actions/cli-action
    # uses: contensis/cli-action@v1
    uses: ./.github/actions/block-push@${{ github.ref_name }}
    # uses: contensis/block-push@v1
    with:
      block-id: node-cli-ci-block
      auto-release: false
      alias: zenhub-dev
      project-id: contensis
      client-id: ${{ secrets.CONTENSIS_CLIENT_ID }}
      shared-secret: ${{ secrets.CONTENSIS_SHARED_SECRET }}
      tag-repo: true

  # test-cli:
  #   name: Test `contensis/cli-action`
  #   needs: build
  #   uses: ./.github/actions/cli-action
  #   # uses: contensis/cli-action@v1
  #   with:
  #     command: get entries
  #     alias: zenhub-dev
  #     project-id: migratortron
  #     client-id: ${{ secrets.CONTENSIS_CLIENT_ID }}
  #     shared-secret: ${{ secrets.CONTENSIS_SHARED_SECRET }}
