name: Docker CI

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/app

jobs:
  build:
    name: Build image and push
    runs-on: ubuntu-latest
    env:
      BUILDER_BASE: node:18-alpine
      APP_BASE: node:18-alpine
      BUILDER_IMAGE: $APP_IMAGE:builder
    steps:
      - uses: actions/checkout@v3

      - name: Log into container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image and push to ${{ env.APP_IMAGE }}:latest
        run: |
          docker pull ${{ env.BUILDER_IMAGE }}
          RESULT=$?
          if [ $RESULT -eq 0 ]; then echo builder image already exists
          else
            docker pull $BUILDER_BASE
            docker tag $BUILDER_BASE ${{ env.BUILDER_IMAGE }}
            docker push ${{ env.BUILDER_IMAGE }}
          fi
          docker pull ${{ env.APP_IMAGE }}:latest
          RESULT=$?
          if [ $RESULT -eq 0 ]; then echo app image already exists
          else
            docker pull $APP_BASE
            docker tag $APP_BASE ${{ env.APP_IMAGE }}:latest
            docker push ${{ env.APP_IMAGE }}:latest
          fi
          docker build -t ${{ env.BUILDER_IMAGE }} --build-arg builder_image=${{ env.BUILDER_IMAGE }} --target prepare -f Dockerfile .
          docker push ${{ env.BUILDER_IMAGE }}
          docker build -t ${{ env.APP_IMAGE }}:latest --build-arg builder_image=${{ env.BUILDER_IMAGE }} --build-arg app_image=${{ env.APP_IMAGE }}:latest -f Dockerfile .
          docker push ${{ env.APP_IMAGE }}:latest

      - name: Push block to Contensis (Test `contensis/block-push` Action)
        id: push-block
        # uses: ./.github/actions/block-push
        uses: contensis/block-push@v1
        with:
          block-id: node-cli-ci-block
          auto-release: false
          alias: zenhub-dev
          project-id: contensis
          client-id: ${{ secrets.CONTENSIS_CLIENT_ID }}
          shared-secret: ${{ secrets.CONTENSIS_SHARED_SECRET }}
          tag-repo: true
          git-token: ${{ github.token }}
          cli-version: latest

      - name: Echo push-block outputs
        run: |
          echo block-version: ${{ steps.push-block.outputs.block-version }}
          echo git-tag: ${{ steps.push-block.outputs.git-tag }}

      - name: Get entries from Contensis (Test `contensis/cli-action`)
        # uses: ./.github/actions/cli-action
        uses: contensis/cli-action@v1
        with:
          command: get entries
          alias: zenhub-dev
          project-id: migratortron
          client-id: ${{ secrets.CONTENSIS_CLIENT_ID }}
          shared-secret: ${{ secrets.CONTENSIS_SHARED_SECRET }}
