name: Publish npm package

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    outputs:
      version:
        description: 'The latest app version in `package.json`'
        value: ${{ jobs.release.outputs.version }}

  workflow_dispatch:
    inputs:
      tag:
        description: 'The NPM version tag to use, "latest" will become the default package version, or "prerelease"'
        required: true
        default: 'latest'

jobs:
  release:
    name: Build package and publish to npm
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.variables.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and set APP_VERSION output variable
        run: |
          yarn run bootstrap
          APP_VERSION=$(node --eval="process.stdout.write(require('./packages/contensis-cli/package.json').version)")
          echo "version=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Publish release package "${{ steps.variables.outputs.version }}" with tag "${{ inputs.tag }}"
        if: inputs.tag != 'prerelease'
        run: |
          cd packages/contensis-cli
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --tag ${{ inputs.tag }} --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
