name: Publish npm package

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    outputs:
      version:
        description: 'The latest app version in `package.json`'
        value: ${{ jobs.release.outputs.version }}

  workflow_dispatch:
    inputs:
      tag:
        description: 'The NPM version tag to use, "latest" will become the default package version, or "prerelease"'
        required: true
        default: 'latest'

jobs:
  release:
    name: Build package and publish to npm
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.app_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - id: build
        name: Install dependencies, build and set APP_VERSION output variable
        run: |
          yarn run bootstrap
          yarn run build

      - id: app_version
        run: |
          APP_VERSION=$(node --eval="process.stdout.write(require('./packages/contensis-cli/package.json').version)")
          echo "version=$APP_VERSION"
          echo "version=$APP_VERSION" >> $GITHUB_OUTPUT

      # - id: publish
      #   name: Install dependencies, build and set APP_VERSION output variable
      #   run: |
      #     npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
      #     npm publish --tag ${{ inputs.tag }} --ignore-scripts --workspace contensis-cli
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
