name: Release version to docker registry

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      APP_VERSION:
        description: 'Release version to tag (e.g. "1.0.0-beta.0" or "2.1.0")'
        required: true

jobs:
  release-docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/app
    steps:
      - uses: actions/checkout@v3

      - name: Log into container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest Docker image and push to ${{ env.APP_IMAGE }}:release
        run: |
          docker pull ${{ env.APP_IMAGE }}:latest
          docker tag ${{ env.APP_IMAGE }}:latest ${{ env.APP_IMAGE }}:release
          docker push ${{ env.APP_IMAGE }}:release
          docker tag ${{ env.APP_IMAGE }}:latest ${{ env.APP_IMAGE }}:${{ inputs.APP_VERSION }}
          docker push ${{ env.APP_IMAGE }}:${{ inputs.APP_VERSION }}
