name: Tag release container
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to tag (e.g. "1.0.0-beta.0" or "2.1.0")'
        required: true

jobs:
  release:
    name: Pull latest and tag release
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.default_branch || github.ref_name }}/app
    steps:
      - name: Log into container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest image
        run: docker pull ${{ env.APP_IMAGE }}:latest

      - name: Tag release and push
        run: |
          docker tag ${{ env.APP_IMAGE }}:latest ${{ env.APP_IMAGE }}:release
          docker push ${{ env.APP_IMAGE }}:release

      - id: app_version
        run: |
          APP_VERSION=$(node --eval="process.stdout.write(require('./packages/contensis-cli/package.json').version)")
          echo "version=$APP_VERSION"

      - name: Tag version and push
        if: steps.build.outputs.version != 'release'
        run: |
          docker tag ${{ env.APP_IMAGE }}:latest ${{ env.APP_IMAGE }}:${{ steps.build.outputs.version }}
          docker push ${{ env.APP_IMAGE }}:${{ steps.build.outputs.version }}

      # - name: Tag version and push
      #   if: inputs.version != 'release'
      #   run: |
      #     docker tag ${{ env.APP_IMAGE }}:latest ${{ env.APP_IMAGE }}:${{ inputs.version }}
      #     docker push ${{ env.APP_IMAGE }}:${{ inputs.version }}
